# -*- coding: utf-8 -*-
"""NEW Copy of INFO450.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UIeGAGKX5OyiNq5JN-94K6ZYUxekvbZk

# Part 1 - Exploratory Data Analysis and Data Preparation

**This version is the updated version (as of 2:30 Apr 20 2026), and uses Tunneling to attempt to get the py app to work in GitHub**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

IPUMS_csv_file_path = 'IPUMS.csv'
OCC_csv_file_path = 'OccupationCodes.csv'

"""Imported all of the libraries and google drive. Mounted google drive so that we can all colaborate on the same notebook."""

df = pd.read_csv('IPUMS.csv')
OCC_df = pd.read_csv('OccupationCodes.csv')

"""converted csv to dataframes"""

df.head()

OCC_df.head()

OCC_df['OCC Code'].info()

df['OCC'].info()

"""Called both of the dataframes so we can see the all of the data and verify what needs to be cleaned. Verify what types of Dtype 'OCC' is in each of the df so we can convert them to match when we merge."""

df = df.dropna()

"""Use df.drop function to drop any invalid rows"""

df['OCC'] = df['OCC'].astype(str)
df = pd.merge(df, OCC_df, left_on='OCC', right_on='OCC Code', how='left')

"""set occ to a string then merged the data"""

df = df[(df['UHRSWORKT'] >= 30) & (df['UHRSWORKT'] <= 60)]
df = df[(df['INCWAGE'] >= 10000) & (df['INCWAGE'] <= 200000)]
df = df[df['WKSWORK1'] > 0]

"""Made three filters

1.   Filters employees who whos usual hours are at least 30 hours and no more than 60
2.   Filters employees whos income is at least 10,000 and nor more than 200000 dollars
3.   Filters employees to ensure that they all worked more than one week

"""

df = df.drop(columns=['Unnamed: 3', 'OCC Code'])
df = df.dropna(subset=['Occupation Title']) # Drop anyone whose job didn't merge

"""Removed unnamed:3 because it was completely empty, dropped occ code since we already had one from the original IPUMS.csv.

Removed "noise variables"
"""

median_income = df['INCWAGE'].median()
df['HighEarner'] = (df['INCWAGE'] > median_income).astype(int)
df["HourlyEfficiency"] = df["INCWAGE"] / (df["WKSWORK1"] * df["UHRSWORKT"])
df["EdWorkIntensity"] = df["EDUC"] * df["UHRSWORKT"]

"""Call the merged df to verify that the occupation description is visible"""

avg_inc_by_occupation = df.groupby('Occupation Title')['INCWAGE'].mean().reset_index()
avg_wage_by_education = df.groupby('EDUC')['INCWAGE'].mean().reset_index()
avg_hours_by_occupation = df.groupby('Occupation Title')['UHRSWORKT'].mean().reset_index()

df

import plotly.express as px

horizontal_bar_chart = px.bar(df['Major Category'].value_counts().reset_index(),
                    x='count',
                    y='Major Category',
                    orientation='h',
                    title='Workforce Distribution: Number of Employees per Sector',
                    labels={'count': 'Number of Employees', 'Major Category': 'Job Sector'},
                    color='Major Category')
horizontal_bar_chart.update_layout(showlegend=False)
horizontal_bar_chart.show()

"""Created a horizontal bar for vis 1. Imported plotly instead of matplot lib since it is interactive. Px.bar to pull the bar chart and used the .value_counts().reset_index() functions to calculate the exact number of employees within each major category. Labeled the axis accordingly with job sector and number of employees. horizontal_bar_chart.update_layout(showlegend=False) gets rid of the legend on the right, the legend was redundant."""

histogram = px.histogram(df,
                    x='UHRSWORKT',
                    title='Workplace Culture: Distribution of Weekly Hours Worked',
                    labels={'UHRSWORKT': 'Hours Worked Per Week', 'count': 'Number of Employees', 'y': 'Number of Employees'},
                    color_discrete_sequence=['#1f77b4'])
histogram.update_layout(yaxis_title="Number of Employees")
histogram.show()

"""Used px.historgram to show how many hours people actually work per week. Unlike the first vis we did, I let plotly automatically count and group the raw data. I used the labels parameter as a translator to turn the code names, like UHRSWORKT, so that the user can read it as Hours Worked Per Week. Had to update the y axis since plotly couldn't translate it from the dictionary.

# Part 2 - Inferential Statistics
"""

import pandas as pd
import numpy as np
from scipy import stats
import math

print(df[['INCWAGE', 'SEX']].describe())
print("Unique SEX values:", df['SEX'].unique())

df = df[(df['INCWAGE'] > 0) & (df['SEX'].isin([1, 2]))]

# 95% Confidence Interval
income = df['INCWAGE']

n = len(income)
mean_income = income.mean()
std_income = income.std()

# standard error
se = std_income / math.sqrt(n)

# the t-value for 95%
t_value = stats.t.ppf(0.975, n-1)

lower = mean_income - t_value * se
upper = mean_income + t_value * se

print("\nConfidence Interval")
print("Mean:", round(mean_income, 2))
print("Lower:", round(lower, 2))
print("Upper:", round(upper, 2))

# comparing the groups
male = df[df['SEX'] == 1]['INCWAGE']
female = df[df['SEX'] == 2]['INCWAGE']

print("\nGroup Means")
print("Male:", round(male.mean(), 2))
print("Female:", round(female.mean(), 2))

# two-sample t-test
t_stat, p_val = stats.ttest_ind(male, female, equal_var=False)

print("\nT-Test Results")
print("t-stat:", round(t_stat, 3))
print("p-value:", round(p_val, 6))

# conclusion
if p_val < 0.05:
    print("\nConclusion: Significant difference between groups")
else:
    print("\nConclusion: No significant difference")

"""The 95% confidence interval shows the range where the true average income is likely to fall. This is useful because it gives more information than just a single mean value.


When comparing the two groups, males had a higher average income than females. However, to determine whether this difference is meaningful, a statistical test was required. The two sample t-tests produced a p-value less than 0.05. This means the difference in average income between males and females is statistically significant.

In simple terms, this suggests that the difference in income between the two groups is unlikely to be due to random chance alone. This is important for the project because it shows that income varies across groups in a measurable and statistically supported way. However, this test does not explain why the difference exists. Other factors such as education, occupation, and work hours may also influence income.

# Part 3 - Predictive Modeling
"""

model_df = df
model_df['HighEarner'] = df['HighEarner']
model_df.head()

model_df['HighEarner'].value_counts()

from sklearn.model_selection import train_test_split

X = model_df[[
    "AGE",
    "SEX",
    "RACE",
    "MARST",
    "OCC",
    "IND",
    "CLASSWKR",
    "EDUC",
    "UHRSWORKT",
    "WKSWORK1",
    "EdWorkIntensity"
]]
y = model_df["HighEarner"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

numeric_features = ["AGE", "UHRSWORKT", "WKSWORK1", "EdWorkIntensity"]
categorical_features = [
    "SEX",
    "RACE",
    "MARST",
    "OCC",
    "IND",
    "CLASSWKR",
    "EDUC"
]

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
preprocess = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"),categorical_features)
    ],
    remainder='passthrough'
)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier

model = Pipeline([
    ("prep", preprocess),
    ("clf",DecisionTreeClassifier(max_depth=10,min_samples_leaf=20))
])

model.fit(X_train,y_train)

from sklearn.tree import export_graphviz
import graphviz

tree = model.named_steps["clf"]
feature_names = model.named_steps["prep"].get_feature_names_out()

dot = export_graphviz(
    tree,
    out_file=None,
    feature_names=feature_names,
    class_names=["Low", "High"],
    filled=True,
    rounded=True,
    special_characters=True,
    max_depth=4
)

graphviz.Source(dot)

y_pred=model.predict(X_test)
y_pred

from sklearn.metrics import confusion_matrix, precision_score, accuracy_score,recall_score

print(confusion_matrix(y_test,y_pred))
print("accuracy", accuracy_score(y_test,y_pred))
print("precision", precision_score(y_test,y_pred))
print("recall",recall_score(y_test,y_pred))

"""We have a good amount of trust in our model because it shows somewhat consistent performance from accuracy to precision and finally recall as they range from around 69% - 72%. Errors are relatively the same across the confusion matrix, showing no heavy bias to one class. However, accuracy is not very high, and since decision trees tend to overfit the model could have trouble generalizing to new data. Overall, our decision tree model is reasonabily reliable but has room for improvement.

# Part 4 - Streamlit App
"""

import streamlit as st
import pandas as pd
import plotly.express as px
# Login with GitHub account here= streamlit.io
# All files & App are uploaded (as of 7pm April 16 2026)


st.title("Workforce Dashboard")

# Bar chart sample
horizontal_bar_chart = px.bar(df['Major Category'].value_counts().reset_index(),
                    x='count',
                    y='Major Category',
                    orientation='h',
                    title='Workforce Distribution: Number of Employees per Sector',
                    labels={'count': 'Number of Employees', 'Major Category': 'Job Sector'},
                    color='Major Category')
horizontal_bar_chart.update_layout(showlegend=False)
horizontal_bar_chart.show()

st.plotly_chart(horizontal_bar_chart)

# Histogram sample
histogram = px.histogram(df,
                    x='UHRSWORKT',
                    title='Workplace Culture: Distribution of Weekly Hours Worked',
                    labels={'UHRSWORKT': 'Hours Worked Per Week', 'count': 'Number of Employees', 'y': 'Number of Employees'},
                    color_discrete_sequence=['#1f77b4'])
histogram.update_layout(yaxis_title="Number of Employees")
histogram.show()

st.plotly_chart(histogram)
st.dataframe(df)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# from google.colab import drive
# 
# # Mount Google Drive to access CSV files
# drive.mount('/content/drive')
# 
# IPUMS_csv_file_path = '/content/drive/MyDrive/INFO450/IPUMS.csv'
# OCC_csv_file_path = '/content/drive/MyDrive/INFO450/OccupationCodes.csv'
# 
# try:
#     df = pd.read_csv(IPUMS_csv_file_path)
#     OCC_df = pd.read_csv(OCC_csv_file_path)
# 
#     # Data Cleaning and Preparation steps (replicated from earlier notebook cells)
#     df = df.dropna()
#     df['OCC'] = df['OCC'].astype(str)
#     df = pd.merge(df, OCC_df, left_on='OCC', right_on='OCC Code', how='left')
#     df = df[(df['UHRSWORKT'] >= 30) & (df['UHRSWORKT'] <= 60)]
#     df = df[(df['INCWAGE'] >= 10000) & (df['INCWAGE'] <= 200000)]
#     df = df[df['WKSWORK1'] > 0]
#     df = df.drop(columns=['Unnamed: 3', 'OCC Code'])
#     df = df.dropna(subset=['Occupation Title'])
# 
#     # Feature Engineering (replicated from earlier notebook cells)
#     median_income = df['INCWAGE'].median()
#     df['HighEarner'] = (df['INCWAGE'] > median_income).astype(int)
#     df["HourlyEfficiency"] = df["INCWAGE"] / (df["WKSWORK1"] * df["UHRSWORKT"])
#     df["EdWorkIntensity"] = df["EDUC"] * df["UHRSWORKT"]
# 
# except FileNotFoundError:
#     st.error("Error: Required CSV files not found. Please ensure 'IPUMS.csv' and 'OccupationCodes.csv' are in your Google Drive.")
#     st.stop()
# except Exception as e:
#     st.error(f"An error occurred during data loading or preprocessing: {e}")
#     st.stop()
# 
# st.title("Workforce Dashboard")
# 
# # Bar chart: Workforce Distribution
# horizontal_bar_chart = px.bar(df['Major Category'].value_counts().reset_index(),
#                     x='count',
#                     y='Major Category',
#                     orientation='h',
#                     title='Workforce Distribution: Number of Employees per Sector',
#                     labels={'count': 'Number of Employees', 'Major Category': 'Job Sector'},
#                     color='Major Category')
# horizontal_bar_chart.update_layout(showlegend=False)
# st.plotly_chart(horizontal_bar_chart)
# 
# # Histogram: Distribution of Weekly Hours Worked
# histogram = px.histogram(df,
#                     x='UHRSWORKT',
#                     title='Workplace Culture: Distribution of Weekly Hours Worked',
#                     labels={'UHRSWORKT': 'Hours Worked Per Week', 'count': 'Number of Employees', 'y': 'Number of Employees'},
#                     color_discrete_sequence=['#1f77b4'])
# histogram.update_layout(yaxis_title="Number of Employees")
# st.plotly_chart(histogram)
# 
# st.dataframe(df)
